WebApplication4/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public string MenuNo { get; set; }
        public Nullable<byte> LinkType { get; set; }
        public string LinkName { get; set; }
        public string LinkURL { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> MenuLevel { get; set; }
        public Nullable<System.DateTime> CeateDate { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}

WebApplication4/Controllers/RoleMaintenanceController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class RoleMaintenanceController : Controller
    {
        SystemDataBaseEntities1 db = new SystemDataBaseEntities1();
        HomeController hc = new HomeController();
        // GET: RoleMaintenance
        public ActionResult Index()
        {
            var roles = db.Roles.ToList();
            var roles2 = db.Roles.ToList();
            List<Role> list = new List<Role>();
            var viewModel = new Role();
            viewModel.ListA = roles;
            viewModel.ListB = list;
            //System.Diagnostics.Debug.WriteLine(roles);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult function(FormCollection form)
        {
            var button = form["button"];
            var roles = db.Roles.ToList();
            var roles2 = db.Roles.ToList();
            var viewModel = new Role();
            var selectRole = form["SelectRole"];
            int loginID = (int)Session["LoginID"];
            var userInfo = db.Users.Where(l => l.UserID == loginID).FirstOrDefault();
            string userName = userInfo.UserName;

            ViewBag.UserNmae = userName;

            if (button == "Query")
            {

                if (selectRole == "All")
                {
                    viewModel.ListA = roles;
                    viewModel.ListB = roles2;
                }
                else
                {
                    roles2 = db.Roles.Where(r => r.RoleName == selectRole).ToList();
                    viewModel.ListA = roles;
                    viewModel.ListB = roles2;
                }
                return View("Index", viewModel);
            }
            else if (button == "Add")
            {
                return View("Add");
            }
            else if (button == "Modify")
            {
                viewModel.ListA = roles;
                ArrayList checkList = new ArrayList();
                roles2.Clear();
                var checkRoleAll = form["checkAll"];
                foreach (var role in roles)
                {
                    var checkRole = form[role.RoleID.ToString()];
                    if (checkRole == "on")
                    {
                        roles2.Add(db.Roles.Where(r => r.RoleID == role.RoleID).FirstOrDefault());
                    }
                }
                System.Diagnostics.Debug.WriteLine(roles2.Count());
                if (roles2.Count() == 1)
                {
                    viewModel.ListB = roles2;
                    return View("Modify", viewModel);
                }
                else if (roles2.Count() == 0)
                {
                    viewModel.ListB = roles2;
                    TempData["SelectionMessage"] = "Plese select atleast one role to modify.";
                    return View("Index", viewModel);
                }
                else
                {
                    roles2 = db.Roles.ToList();
                    viewModel.ListB = roles2;
                    TempData["SelectionMessage"] = "Plese modify one role at a time.";
                    return View("Index", viewModel);
                }
            }
            else if (button == "Menu")
            {
                List<Menu> MenuList = new List<Menu>();
                MenuList = db.Menus.ToList();

                viewModel.ListA = roles;
                roles2.Clear();
                var checkRoleAll = form["checkAll"];
                foreach (var role in roles)
                {
                    var RoleTest = viewModel.Menus.ToList();

                    
                    var checkRole = form[role.RoleID.ToString()];
                    if (checkRole == "on")
                    {
                        roles2.Add(db.Roles.Where(r => r.RoleID == role.RoleID).FirstOrDefault());
                    }
                }
                if (roles2.Count() == 1)
                {
                    var RoleTest = roles2.First().Menus.ToList();
                    viewModel.ListB = roles2;
                    viewModel.ListMenu = RoleTest;
                    viewModel.AllMenu = MenuList; 

                    return View("Menu", viewModel);
                }
                else if (roles2.Count() == 0)
                {
                    viewModel.ListB = roles2;
                    TempData["SelectionMessage"] = "Plese atleast one role to modify its menu list.";
                    return View("Index", viewModel);
                }
                else
                {
                    roles2 = db.Roles.ToList();
                    viewModel.ListB = roles2;
                    TempData["SelectionMessage"] = "Plese modify one role's menu list at a time.";
                    return View("Index", viewModel);
                }
            }
            else if (button == "Delete")
            {
                viewModel.ListA = roles;
                ArrayList checkList = new ArrayList();
                roles2.Clear();
                var checkRoleAll = form["checkAll"];
                Role dropRole = new Role();
                foreach (var role in roles)
                {
                    var checkRole = form[role.RoleID.ToString()];
                    if (checkRole == "on")
                    {
                        dropRole = db.Roles.Where(r => r.RoleID == role.RoleID).FirstOrDefault();
                        db.Roles.Remove(dropRole);
                        db.SaveChanges();
                    }               
                }
                //roles2 = db.Roles.ToList();
                if (roles2.Count() == 0)
                {
                    viewModel.ListB = roles2;
                    return View("Index", viewModel);
                }
                else
                {
                    db.SaveChanges();
                    roles = db.Roles.ToList();
                    roles2 = db.Roles.ToList();
                    viewModel.ListA = roles;
                    viewModel.ListB = roles2;
                    return View("Index", viewModel);
                }
            }
            return View("Index", viewModel);
        }

        public ActionResult Add(FormCollection form, Role role)
        {
            var roles = db.Roles.ToList();
            var roles2 = db.Roles.ToList();
            var viewModel = new Role();
            viewModel.ListA = roles;
            viewModel.ListB = roles2;

            int loginID = (int)Session["LoginID"];
            var userInfo = db.Users.Where(l => l.UserID == loginID).FirstOrDefault();
            string userName = userInfo.UserName;

            var selectStatus = form["SelectStatus"];
            if (selectStatus == "Y")
            {
                role.Status = 1;
            }
            else { role.Status = 0; }
            DateTime myDateTime = DateTime.Now;
            string sqlFormattedDate = myDateTime.Date.ToString("yyyy-MM-dd HH:mm:ss");
            role.CreateDate = Convert.ToDateTime(sqlFormattedDate);
            role.CreateUser = userName;
            role.ModifyDate = Convert.ToDateTime(sqlFormattedDate);
            role.ModifyUser = userName;

            db.Roles.Add(role);
            db.SaveChanges();

            roles = db.Roles.ToList();
            roles2 = db.Roles.ToList();
            viewModel.ListA = roles;
            viewModel.ListB = roles2;

            return View("Index", viewModel);
        }

        public ActionResult Modify(FormCollection form, Role role)
        {
            var roles = db.Roles.ToList();
            var roles2 = db.Roles.ToList();
            var viewModel = new Role();
            viewModel.ListA = roles;
            viewModel.ListB = roles2;
            String roleName = form["Origin-Role-Name"];
            int loginID = (int)Session["LoginID"];

            var userInfo = db.Users.Where(l => l.UserID == loginID).FirstOrDefault();
            string userName = userInfo.UserName;

            Role Role_to_update = db.Roles.SingleOrDefault(r => r.RoleName == roleName);

            Role_to_update.RoleName = roleName;
            Role_to_update.RoleDescription = role.RoleDescription;
            var selectStatus = form["SelectStatus"];
            if (selectStatus == "Y")
            {
                Role_to_update.Status = 1;
            }
            else { Role_to_update.Status = 0; }
            DateTime myDateTime = DateTime.Now;
            string sqlFormattedDate = myDateTime.Date.ToString("yyyy-MM-dd HH:mm:ss");
            Role_to_update.ModifyDate = Convert.ToDateTime(sqlFormattedDate);
            Role_to_update.ModifyUser = userName;
            db.SaveChanges();

            roles = db.Roles.ToList();
            roles2 = db.Roles.ToList();
            viewModel.ListA = roles;
            viewModel.ListB = roles2;

            return View("Index", viewModel);
        }

        public ActionResult Menu(FormCollection form, Role role)
        {
            var roles = db.Roles.ToList();
            var roles2 = db.Roles.ToList();
            var viewModel = new Role();
            viewModel.ListA = roles;
            viewModel.ListB = roles2;
            List<Menu> MenuList = new List<Menu>();
            MenuList = db.Menus.ToList();

            String roleName = form["Origin-Role-Name"];

            Role select_role = db.Roles.SingleOrDefault(r => r.RoleName == roleName);

            var Role_Menu = select_role.Menus.ToList();

            Menu saveRoleMenu = new Menu();
            Role saveMenuRole = new Role();
            foreach (var menu in Role_Menu)
            {
                var checkMenu_delete = form[menu.MenuNo];
                if (checkMenu_delete == null)
                {

WebApplication4/Controllers/SystemSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class SystemSetupController : Controller
    {
        SystemDataBaseEntities1 db = new SystemDataBaseEntities1();
        
        // GET: SystemSetup
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserMaintain()
        {
            return RedirectToAction("Index", "UserMaintenance");
        }

        public ActionResult RoleMaintain()
        {
            return RedirectToAction("Index", "RoleMaintenance");
        }

        public ActionResult MenuMaintain()
        {
            return RedirectToAction("Index", "MenuMaintenance");
        }
    }
}

WebApplication4/Views/RoleMaintenance/Add.cshtml
@model WebApplication4.Models.Role
@*@model IEnumerable<WebApplication4.Models.Role>*@
@{
    Layout = null;
    if (Session["LoginID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RoleMaintenance</title>
    <style>
        body {
            font-family: "Lato", sans-serif;
        }

        /* Fixed sidenav, full height */
        .sidenav {
            height: 100%;
            width: 300px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

            /* Style the sidenav links and the dropdown button */
            .sidenav a, .dropdown-btn {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 20px;
                color: #818181;
                display: block;
                border: none;
                background: none;
                width: 100%;
                text-align: left;
                cursor: pointer;
                outline: none;
            }

                /* On mouse-over */
                .sidenav a:hover, .dropdown-btn:hover {
                    color: #f1f1f1;
                }

        /* Main content */
        .main {
            margin-left: 300px; /* Same as the width of the sidenav */
            font-size: 20px; /* Increased text to enable scrolling */
            padding: 0px 10px;
        }

        /* Add an active class to the active dropdown button */
        .active {
            background-color: green;
            color: white;
        }

        /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
        .dropdown-container {
            display: none;
            background-color: #262626;
            padding-left: 8px;
        }

        /* Optional: Style the caret down icon */
        .fa-caret-down {
            float: right;
            padding-right: 8px;
        }
    </style>
</head>
<body>
    <div class="sidenav">
        <a href="@Url.Action("ReturnHome", "Home")">Home</a>
        <button class="dropdown-btn">
            System Setup
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="@Url.Action("UserMaintain", "SystemSetup")">User Maintenance</a>
            <a href="@Url.Action("RoleMaintain", "SystemSetup")">Role Maintenance</a>
            <a href="@Url.Action("MenuMaintain", "SystemSetup")">Menu Maintenance</a>
        </div>

        <button class="dropdown-btn">
            System Operation
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
        </div>

        <button class="dropdown-btn">
            Profile
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="@Url.Action("ChangePassword", "Home")">Change Password</a>
            <a href="@Url.Action("LogOut", "Home")"> LogOut</a>
        </div>
    </div>

    <div class="main">
        <h2>Role Maintenance --> Add</h2>
        @using (Html.BeginForm("Add", "RoleMaintenance", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>@Html.LabelFor(model => model.RoleName)</td>
                    <td>@Html.EditorFor(model => model.RoleName)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.RoleDescription)</td>
                    <td>@Html.EditorFor(model => model.RoleDescription)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Status)</td>
                    <td>
                        <select name="SelectStatus">
                            <option>Y</option>
                            <option>N</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" name="name" value="Save" />
                        <input type="button" value="Back" onclick="history.back()">
                    </td>
                </tr>


            </table>
        }
    </div>

    <script>
        /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }

        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</body>
</html>

WebApplication4/Views/RoleMaintenance/Index.cshtml
@model WebApplication4.Models.Role
@*@model IEnumerable<WebApplication4.Models.Role>*@
@{
    Layout = null;
    if (Session["LoginID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RoleMaintenance</title>
    <style>
        body {
            font-family: "Lato", sans-serif;
        }

        /* Fixed sidenav, full height */
        .sidenav {
            height: 100%;
            width: 300px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

            /* Style the sidenav links and the dropdown button */
            .sidenav a, .dropdown-btn {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 20px;
                color: #818181;
                display: block;
                border: none;
                background: none;
                width: 100%;
                text-align: left;
                cursor: pointer;
                outline: none;
            }

                /* On mouse-over */
                .sidenav a:hover, .dropdown-btn:hover {
                    color: #f1f1f1;
                }

        /* Main content */
        .main {
            margin-left: 300px; /* Same as the width of the sidenav */
            font-size: 20px; /* Increased text to enable scrolling */
            padding: 0px 10px;
        }

        /* Add an active class to the active dropdown button */
        .active {
            background-color: green;
            color: white;
        }

        /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
        .dropdown-container {
            display: none;
            background-color: #262626;
            padding-left: 8px;
        }

        /* Optional: Style the caret down icon */
        .fa-caret-down {
            float: right;
            padding-right: 8px;
        }

        table {
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }

        th {
            cursor: pointer;
        }

        th, td {
            text-align: left;
            padding: 16px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }


    </style>
</head>
<body>
    <div class="sidenav">
        <a href="@Url.Action("ReturnHome", "Home")">Home</a>
        <button class="dropdown-btn">
            System Setup
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="@Url.Action("UserMaintain", "SystemSetup")">User Maintenance</a>
            <a href="@Url.Action("RoleMaintain", "SystemSetup")">Role Maintenance</a>
            <a href="@Url.Action("MenuMaintain", "SystemSetup")">Menu Maintenance</a>
        </div>

        <button class="dropdown-btn">
            System Operation
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
        </div>

        <button class="dropdown-btn">
            Profile
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href="@Url.Action("ChangePassword", "Home")">Change Password</a>
            <a href="@Url.Action("LogOut", "Home")"> LogOut</a>
        </div>
    </div>

    <div class="main">
        <h2>Role Maintenance</h2>
        @using (Html.BeginForm("function", "RoleMaintenance", FormMethod.Post))
        {
            if (TempData["SelectionMessage"] != null)
            {
                <script>
                alert('@TempData["SelectionMessage"]');
                </script>
            }
            <table>
                <tr>
                    <td>Role</td>
                    <td></td>
                    <td>
                        <select name="SelectRole">
                            <option>All</option>
                            @foreach (var item in Model.ListA)
                            {
                                <option> @item.RoleName</option>
                            }
                        </select>
                    </td>
                </tr>
            </table>
            <table>
                <tr>
                    <td><input type="submit" name="button" value="Query" /></td>
                    <td><input type="submit" name="button" value="Add" /></td>
                    <td><input type="submit" name="button" value="Modify" /></td>
                    <td><input type="submit" name="button" value="Menu" /></td>
                    <td><input type="submit" name="button" value="Delete" onClick = "return confirm('Press a button!')" /></td>
                    
                </tr>
            </table>


            <table id="RoleTable">
                <tr>
                    <td><input type="checkbox" name="checkAll"></td>
                    <th onclick="sortTable(0)"> Role Name</th>
                    <td></td>
                    <th onclick="sortTable(1)"> Role Description</th>
                    <td></td>
                    <th onclick="sortTable(2)"> Status</th>
                    <td></td>
                    <th onclick="sortTable(3)"> Create Date</th>
                    <td></td>
                    <th onclick="sortTable(4)"> Create User</th>
                    <td></td>
                    <th onclick="sortTable(5)"> Modify Date</th>
                    <td></td>
                    <th onclick="sortTable(6)"> Modify User</th>
                </tr>
                @foreach (var item in Model.ListB)
                {

                    <tr>
                        <td><input type="checkbox" name=@item.RoleID.ToString()></td>
                        <td>@item.RoleName</td>
                        <td></td>
                        <td>@item.RoleDescription</td>
                        <td></td>
                        @if (@item.Status == 0)
                        {
                            <td>N</td>
                        }
                        else
                        {
                            <td>Y</td>
                        }
                        <td></td>
                        <td>@item.CreateDate.ToString().AsDateTime().ToString("yyyy/MM/dd")</td>
                        <td></td>
                        <td>@item.CreateUser</td>
                        <td></td>
                        <td>@item.ModifyDate.ToString().AsDateTime().ToString("yyyy/MM/dd")</td>
                        <td></td>
                        <td>@item.ModifyUser</td>
                    </tr>
                }
            </table>

        }
    </div>

    <script>
        /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }

        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("RoleTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 1; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }

    </script>
</body>
</html>